"""change model posts, add img

Revision ID: ff189e7cb133
Revises: 13d86f294a73
Create Date: 2025-07-18 21:25:30.929768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff189e7cb133'
down_revision: Union[str, Sequence[str], None] = '13d86f294a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Добавить столбец как nullable и с дефолтом
    op.add_column('posts', sa.Column('img', sa.String(length=100), nullable=True, server_default='default_img'))

    # 2. (опционально) Обновить все старые строки, если нужно другое значение
    # op.execute("UPDATE posts SET img = 'default_img' WHERE img IS NULL")

    # 3. Сделать столбец NOT NULL
    op.alter_column('posts', 'img', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'img')
    # ### end Alembic commands ###
